# Generated by Django 3.2.4 on 2021-11-22 10:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='更新时间')),
                ('contents', mdeditor.fields.MDTextField(verbose_name='关于Text')),
            ],
            options={
                'verbose_name': '关于',
                'verbose_name_plural': '关于',
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='更新时间')),
                ('head_announcement', models.CharField(default='热烈欢迎浏览本站', max_length=30, verbose_name='头部轮播公告')),
                ('main_announcement', models.TextField(blank=True, default='暂无公告......', max_length=300, null=True, verbose_name='右侧公告')),
            ],
            options={
                'verbose_name': '公告',
                'verbose_name_plural': '公告',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=200, verbose_name='文章标题')),
                ('date_time', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('content', mdeditor.fields.MDTextField(blank=True, null=True, verbose_name='文章正文')),
                ('digest', models.TextField(blank=True, null=True, verbose_name='文章摘要')),
                ('view', models.BigIntegerField(db_index=True, default=0, verbose_name='阅读数')),
                ('comment', models.BigIntegerField(default=0, verbose_name='评论数')),
                ('picture', models.CharField(blank=True, max_length=300, null=True, verbose_name='url(标题图链接)')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'verbose_name': '博客文章',
                'verbose_name_plural': '博客文章',
                'ordering': ['-date_time'],
            },
        ),
        migrations.CreateModel(
            name='ArticleImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='更新时间')),
                ('img_title', models.CharField(max_length=50, verbose_name='图片标题')),
                ('article_img', models.ImageField(upload_to='article_img', verbose_name='文章大头图')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='更新时间')),
                ('carousel', models.ImageField(upload_to='carousel', verbose_name='轮播图')),
                ('carousel_title', models.TextField(blank=True, max_length=100, null=True, verbose_name='轮播图左下标题')),
                ('img_link_title', models.TextField(blank=True, max_length=100, null=True, verbose_name='图片标题')),
                ('img_alt', models.TextField(blank=True, max_length=100, null=True, verbose_name='轮播图alt')),
            ],
            options={
                'verbose_name': '首页轮播图配置',
                'verbose_name_plural': '首页轮播图配置',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=30, verbose_name='文章类型')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_mod_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '文章类型',
                'verbose_name_plural': '文章类型',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Conf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='更新时间')),
                ('main_website', models.CharField(default='', max_length=64, verbose_name='主网站')),
                ('name', models.CharField(default='', max_length=32, verbose_name='关注我_名称')),
                ('chinese_description', models.CharField(default='', max_length=128, verbose_name='关注我_中文描述')),
                ('english_description', models.TextField(default='', max_length=128, verbose_name='关注我_英文描述')),
                ('avatar', models.ImageField(upload_to='avatar', verbose_name='我的头像')),
                ('website_author', models.CharField(default='', max_length=20, verbose_name='网站作者')),
                ('website_author_link', models.CharField(default='', max_length=200, verbose_name='网站作者链接')),
                ('email', models.EmailField(default='', max_length=50, verbose_name='作者收件邮箱')),
                ('website_number', models.CharField(default='', max_length=100, verbose_name='备案号')),
                ('git', models.CharField(default='', max_length=100, verbose_name='git链接')),
                ('website_logo', models.ImageField(default='', upload_to='logo', verbose_name='网站logo')),
                ('donate_img', models.ImageField(default='', upload_to='donate', verbose_name='捐助二维码')),
            ],
            options={
                'verbose_name': '网站配置',
                'verbose_name_plural': '网站配置',
            },
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='更新时间')),
                ('url', models.CharField(default='', max_length=200, verbose_name='友链链接')),
                ('title', models.CharField(default='', max_length=100, verbose_name='超链接title')),
                ('name', models.CharField(default='', max_length=20, verbose_name='友链名称')),
            ],
            options={
                'verbose_name': '友链',
                'verbose_name_plural': '友链',
            },
        ),
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='更新时间')),
                ('payimg', models.ImageField(blank=True, null=True, upload_to='pay', verbose_name='捐助收款图')),
            ],
            options={
                'verbose_name': '捐助收款图',
                'verbose_name_plural': '捐助收款图',
            },
        ),
        migrations.CreateModel(
            name='SiteUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='更新时间')),
                ('username', models.CharField(max_length=200, unique=True, verbose_name='账号')),
                ('password', models.CharField(max_length=200, verbose_name='密码')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='邮箱')),
                ('time_joined', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
                'ordering': ['time_joined'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='更新时间')),
                ('email', models.EmailField(max_length=200, verbose_name='邮箱订阅用户')),
                ('sub_time', models.DateTimeField(auto_now_add=True, verbose_name='订阅时间')),
            ],
            options={
                'verbose_name': '邮箱订阅',
                'verbose_name_plural': '邮箱订阅',
                'ordering': ['sub_time'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='更新时间')),
                ('tag_name', models.CharField(max_length=30, verbose_name='标签名称')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='更新时间')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='users_avatar', verbose_name='用户头像')),
                ('mobile', models.IntegerField(blank=True, null=True, validators=[django.core.validators.RegexValidator('^1[3-9]\\d{9}$', '手机号码格式不正确')], verbose_name='手机号')),
                ('wechat', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='微信')),
                ('qq', models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='QQ')),
                ('blog_address', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='博客地址')),
                ('introduction', models.TextField(blank=True, default='', max_length=500, null=True, verbose_name='自我介绍')),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.siteuser')),
            ],
            options={
                'verbose_name': '用户扩展信息',
                'verbose_name_plural': '用户扩展信息',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('user_name', models.CharField(max_length=25, verbose_name='评论用户')),
                ('email', models.EmailField(default='', max_length=50, verbose_name='预留邮箱')),
                ('url', models.CharField(max_length=200, verbose_name='链接')),
                ('url_input', models.CharField(default='', max_length=100, verbose_name='输入链接拼接')),
                ('comment', models.TextField(max_length=500, verbose_name='评论内容')),
                ('post', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='post', to='blog.article')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
                'ordering': ['create_time'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.category', verbose_name='文章类型'),
        ),
        migrations.AddField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(to='blog.Tag'),
        ),
    ]
