# Generated by Django 3.2.4 on 2021-11-22 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conf',
            name='chinese_description',
            field=models.CharField(default='', max_length=128, verbose_name='关注我_中文描述'),
        ),
        migrations.AlterField(
            model_name='conf',
            name='english_description',
            field=models.TextField(default='', max_length=128, verbose_name='关注我_英文描述'),
        ),
        migrations.AlterField(
            model_name='conf',
            name='name',
            field=models.CharField(default='', max_length=32, verbose_name='关注我_名称'),
        ),
    ]
